version: '3.7'
services:
  db-social-bot:
    image: postgres:11.5
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: social-bot
    ports:
      - '5432:5432'

  redis-social-bot:
    image: redis:4.0.5-alpine
    command: ['redis-server', '--appendonly', 'yes']
    hostname: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

networks:
  redis-net:

volumes:
  redis-data:
